
# Path of cryptogen tool. Can be omitted.
cryptogenPath: "/home/giou/go/src/github.com/fabric/fabric-samples/bin/cryptogen"

# Peer array with domains.
peers:
  - peer0.org1.example.com
  - peer1.org1.example.com
  - peer0.org2.example.com
  - peer1.org2.example.com

# Orderer array with domains.
orderers:
  - orderer0.org1.example.com
  - orderer0.org2.example.com
