
# Path of cryptogen tool. Can be omitted if cryptogen is exported to $PATH.
hfToolPath: "/home/giou/go/src/github.com/hyperledger/fabric-samples/bin"
channelName: "giouchannel"
consensusType: "etcdraft"

orgs:
  -
    name: org1
    # Peer array with domains.
    peers:
       -
         name: peer0.org1.example.com
       -
         name: peer1.org1.example.com
    orderers:
       -
         name: orderer1.example.com
  -
    name: org2
    peers:
      -
        name: peer0.org2.example.com
      -
        name: peer1.org2.example.com
    orderers:
      -
        name: orderer2.example.com