
# Path of cryptogen tool. Can be omitted if cryptogen is exported to $PATH.
hfToolPath: "/home/giou/go/src/github.com/hyperledger/fabric-samples/bin"
channelName: "giouchannel"
consensusType: "etcdraft"

orgs:
  - name: ordererOrgs
    orderers:
      - name: orderer1.example.com
        port: 7050
      - name: orderer2.example.com
        port: 7051
      - name: orderer3.example.com
        port: 7052
      - name: orderer4.example.com
        port: 7053
      - name: orderer5.example.com
        port: 7054
  - name: org1
    # Peer array with domains.
    peers:
       - name: peer0.org1.example.com
       - name: peer1.org1.example.com
#    orderers:
#       -
#         name: orderer1.example.com
  - name: org2
    peers:
      - name: peer0.org2.example.com
      - name: peer1.org2.example.com
#    orderers:
#      -
#        name: orderer2.example.com